nusers: 10 ## number of users
nitems: 100 ## number of items
nratings: 1000 ## number of ratings
ncategories: 5 ## number of item categories
data_type: "synthetic"
policy: "GaussianProcess"

emb_dim: 2 ## item embedding size
k: 2 ## number of items to sample at each time
seed: 1234 ## random seed
horizon: 10000 ## recommendation rounds

S: 1. ## norm on item embeddings
Sp: 1. ## norm on model parameter
m: 1 ## feedback bound
sigma: 0.5 ## variance in reward noise

ndec: 3 ## number of decimals to print out
ntests: 10000 ## number of samples to compare distributions
gamma: 1.0 ## discounting factor for the time
