nusers: 20       ## number of users
nitems: 100      ## number of items
nratings: 1000   ## number of ratings
ncategories: 5   ## number of item categories
data_type: "synthetic"
policies: ["LogisticUCB","LogisticUCBDiversity"]

emb_dim: 10      ## item embedding size
emb_dim_user: 10 ## user embeddings size
k: 3             ## number of items to sample at each time
seed: 1234       ## random seed
horizon: 100     ## recommendation rounds
verbose: false
prob_new_user: 0.

S: 1.            ## norm on item embeddings
Sp: 1.           ## norm on model parameter
m: 1             ## feedback bound
sigma: 0.5       ## variance in reward noise

ndec: 3          ## number of decimals to print out
niters: 3        ## number of iterations
njobs: 1         ## number of parallel jobs
gamma: 1.0       ## discounting factor for the time
